#if !defined(AFX_EDITEXT_H__0DF27FF6_A17D_4CDA_AE60_FAC4C9ECFCB4__INCLUDED_)
#define AFX_EDITEXT_H__0DF27FF6_A17D_4CDA_AE60_FAC4C9ECFCB4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CEditExt wrapper class
namespace acm{
class CEditExt : public CWnd
{
protected:
	DECLARE_DYNCREATE(CEditExt)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xd310073e, 0x97ac, 0x49fa, { 0x94, 0x5d, 0xe2, 0x63, 0x76, 0x2f, 0x39, 0xe5 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	unsigned long GetBackColor();
	void SetBackColor(unsigned long);
	long GetBorderStyle();
	void SetBorderStyle(long);
	unsigned long GetForeColor();
	void SetForeColor(unsigned long);
	long GetTextFormat();
	void SetTextFormat(long);
	long GetDecimaldigits();
	void SetDecimaldigits(long);
	CString GetText();
	void SetText(LPCTSTR);
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	BOOL GetReadOnly();
	void SetReadOnly(BOOL);

// Operations
public:
	void AboutBox();
	VARIANT GetValue();
	void SetValue(const VARIANT& vvar);
};


}
//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_EDITEXT_H__0DF27FF6_A17D_4CDA_AE60_FAC4C9ECFCB4__INCLUDED_)
